apps/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'


urlpatterns = [
    ######################
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    ######################
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/<str:uuid>/', views.room, name='room'),
    path('chat-admin/<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.chat.urls')),
    # path('', include('apps.account.urls')),
    path('admin/', admin.site.urls),
]

apps/chat/models.py
from django.db import models

from django.contrib.auth.models import User


class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ('created_at',)
    
    def __str__(self):
        return f'{self.sent_by}'


class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    CHOICES_STATUS = (
        (WAITING, 'En espera'),
        (ACTIVE, 'Activo'),
        (CLOSED, 'Cerrado'),
    )

    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)
    
    def __str__(self):
        return f'{self.client} - {self.uuid}'

apps/chat/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from django.contrib.auth.models import User

from .models import Room

######################
def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')
######################

@require_POST
def create_room(request, uuid):
    username = request.POST.get('username', '')
    url = request.POST.get('url', '')

    Room.objects.create(uuid=uuid, client=username, url=url)

    return JsonResponse({'message': 'Sala creada'})


@login_required
def admin(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)

    return render(request, 'chat/admin.html', {
        'rooms': rooms,
        'users': users
    })


@login_required
def room(request, uuid):
    room = Room.objects.get(uuid=uuid)

    if room.status == Room.WAITING:
        room.status = Room.ACTIVE
        room.agent = request.user
        room.save()

    return render(request, 'chat/room.html', {
        'room': room
    })


@login_required
def delete_room(request, uuid):
    if request.user.has_perm('room.delete_room'):
        room = Room.objects.get(uuid=uuid)
        room.delete()
                
        messages.success(request, 'Chat fue Eliminado')

        return redirect('/chat-admin/')
    else:
        messages.error(request, '¡No tienes acceso para eliminar habitaciones!')

        return redirect('/chat-admin/')

templates/chat/admin.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-2xl">Administrador de Chats</h1>
<!---->
    {% if perms.user.add_user %}
        <div class="mt-8">
            <h2 class="mb-4 text-lg">Usuarios</h2>

            <div class="mt-6">
                {% for user in users %}
                    <div class="grid grid-cols-4 gap-4 py-2 {% cycle 'bg-gray-100' '' %}">

                        <p class="px-2">{{ user.username }}</p>
                        <p class="px-2">{{ user.email }}</p>


                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}


    <hr class="my-6">

    <div class="mt-8">
        <h2 class="mb-4 text-lg">Salas</h2>

        {% include 'chat/partials/room_list.html' %}
    </div>
{% endblock %}

templates/chat/partials/chat_bubble.html
<div id="chat" class="max-w-[300px] fixed right-2 bottom-2 p-4 bg-white border border-gray-300 rounded-xl">
    <div id="chat_icon">
        <button id="chat_open" class="w-[50px] flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" class="text-rose-600">
                <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155" />
            </svg>              
        </button>
    </div>

    <div id="chat_welcome" class="hidden">
        <input type="text" name="username" id="chat_name" class="w-full mb-4 py-2 px-6 rounded-xl bg-gray-100" placeholder="Tu nombre...">

        <button id="chat_join" class="py-2 px-6 rounded-xl text-white bg-rose-600">Unirse a chats</button>
    </div>

    <div id="chat_room" class="hidden">
        <div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll">
            <p>¡Bienvenidos a nuestro chat! Por favor escriba su mensaje y espere a que un agente se una...</p>
        </div>

        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Escribe tu mensaje...">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl">Enviar</button>
    </div>
</div>

templates/chat/partials/room_list.html
<div class="grid grid-cols-4 gap-4">
    {% for room in rooms %}
        <div class="p-4 rounded-xl {% if room.status == 'waiting' %}bg-emerald-100{% elif room.status == 'active' %}bg-yellow-100{% else %}bg-gray-100{% endif %}">
            <h3 class="mb-4 text-lg">Chat</h3>

            <p>
                <b>ID: </b>{{ room.uuid }}<br>
                <b>Cliente: </b>{{ room.client }}<br>
                <b>Estado: </b>{{ room.get_status_display }}<br>
                <b>Agente: </b>{% firstof room.agent.username 'Ningun Agente...' %}
            </p>

            <a href="{% url 'chat:room' room.uuid %}" class="mt-4 inline-block py-2 px-6 bg-emerald-800 text-white rounded-xl">Entrar</a>

            <a href="{% url 'chat:delete_room' room.uuid %}" class="mt-4 inline-block py-2 px-6 bg-rose-800 text-white rounded-xl">Eliminar</a>
        </div>
    {% endfor %}
</div>

templates/chat/room.html
{% extends 'core/base.html' %}

{% load static chatextras %}

{% block content %}
    <h1 class="text-2xl">Sala "{{ room.uuid }}"</h1>

    <hr class="my-6">

    <p class="mb-6">
        <b>Nombre: </b>{{ room.client }}<br>
        <b>Tiempo: </b>{{ room.created_at|timesince }}<br>
        <b>Estado: </b>{{ room.get_status_display }}<br>
        <b>Url: </b>{{ room.url }}<br>
        <b>Agente: </b>{% firstof room.agent.username 'Ningun Agente...' %}
    </p>

    <hr class="mb-6">

    <div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll flex flex-col flex-grow">
        {% for message in room.messages.all %}
            <div class="flex w-full max-w-md mt-2 space-x-3 {% if message.created_by %}ml-auto justify-end{% endif %}">
                {% if not message.created_by %}
                    <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 text-center pt-2">
                        {{ message.sent_by|initials }}
                    </div>
                {% endif %}

                <div>
                    <div class="p-4 rounded-xl {% if message.created_by %}bg-blue-600 text-white{% else %}bg-gray-300{% endif %}">
                        <p class="text-sm">{{ message.body }}</p>
                    </div>

                    <span class="text-xs text-gray-500 leading-none">{{ message.created_at|timesince }}</span>
                </div>

                {% if message.created_by %}
                    <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 text-center pt-2">
                        {{ message.sent_by|initials }}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    {% if room.status == 'active' %}
        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Escribir tu mensaje...">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl">Enviar</button>
    {% endif %}
{% endblock %}

{% block scripts %}
    {% if room.status == 'active' %}
        {{ room.uuid|json_script:'room_uuid' }}
        {{ request.user.username|json_script:'user_name' }}
        {{ request.user.id|json_script:'user_id' }}

        <script src="{% static 'js/main_admin.js' %}"></script>
    {% endif %}
{% endblock %}

templates/chat/user_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-2xl">{{ user.username }}</h1>

    <hr class="my-6">

    <div class="mt-8">
        <h2 class="mb-4 text-lg">Sala</h2>

        {% include 'chat/partials/room_list.html' %}
    </div>
{% endblock %}

templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class="mb-6 text-2xl">About</h1>
{% endblock %}

templates/core/base.html
{% load static %}

<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
    </head>

    <body>
        <div class="p-2">
            <nav class="p-6 bg-rose-600 text-white flex justify-between items-center rounded-xl">
                <a href="{% url 'chat:index' %}" class="text-xl">inicio</a>

                <div class="flex items-center space-x-4">
                    <!-- 
                    <a href="{% url 'chat:index' %}">Home</a>
                    <a href="{% url 'chat:about' %}">About</a>
                    -->
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'chat:admin' %}" class="inline-block py-4 px-6 bg-rose-800 text-white rounded-xl">Administrador</a>
                    {% endif %}
                </div>
            </nav>

            <main class="max-w-6xl mx-auto p-6">
                {% if messages %}
                    <div class="message mb-6 p-6 bg-gray-800 text-white rounded-xl">
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                {% block content %}
                {% endblock %}
            </main>
        </div>

        <footer class="py-12 px-6 bg-gray-800 text-white text-center text-xs">
            <p>Copyright (c) 2023 - Jatte</p>
        </footer>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
    <div class="mt-12 py-12 px-8 grid grid-cols-5 gap-4 items-center border border-rose-200 rounded-xl">
        <div class="col-span-2">
            <img src="{% static 'images/header.png' %}">
        </div>

        <div class="col-span-3">
            <h1 class="mb-8 text-3xl">Welcome to Jatte</h1>

            <h2 class="text-lg text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor. Suspendisse vitae augue dolor. Nunc sed eleifend nulla.</h2>
        </div>
    </div>

    <div class="mt-12 py-12 px-8 grid grid-cols-3 gap-4 items-center">
        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>
    </div>

    {% include 'chat/partials/chat_bubble.html' %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}